### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by wimmelstein** [Zarmina/java_advanced#1]
- You have an id as int for your model. If the id is numeric, it's usually of type long.
- You have an all-arguments constructor, including the id. That's unusual. I would take away the id from the constructor, and create a new one... something like: this.id = <insert id generator>.
- Finding a car by id now results null if the car is not found. I would suggest using Optional<Car>. That way you can check for null, and decide whether to throw an exception or not.
- deleteCars... that's an elegant way of removing it from the list.
- http status for succesful deletion is recommended to be 204 (if you don't want to send additional information in the body, which is usually the case)
- I would advise against using INTERNAL_SERVER_ERROR, because that's when the server cannot process your request, and since your are catching some other exception, you are handling it. I would suggest BAD_REQUEST, or maybe better NOT_FOUND.
- The way you're doing @GetMapping, @PostMapping, etc. is equivalent to what my code does. I'm using @RequestMapping for clarity with teaching. This way you know what it does and what it produces/consumes. 

This may be a little more than you thought, but your code in general looks good.

**Comment by Zarmina** [comment]
Thank you for the feedback i will update my code accordingly :)
